[env:xiao_nrf52840]
platform = https://github.com/maxgerhardt/platform-nordicnrf52.git
board = xiaoble_adafruit
framework = arduino
monitor_speed = 115200

lib_deps =
    jgromes/RadioLib
    bblanchon/ArduinoJson@^6.21.5
    adafruit/Adafruit MCP23017 Arduino Library
    adafruit/Adafruit BusIO
    adafruit/Adafruit SleepyDog Library
